# Generated by Django 5.1 on 2024-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
